<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://apache.org">  
  <modelVersion>4.0.0</modelVersion>  
  <groupId>com.finance</groupId>  
  <artifactId>smart-loan-system</artifactId>  
  <version>1.0-SNAPSHOT</version>  
  <properties>    
    <maven.compiler.source>17</maven.compiler.source>    
    <maven.compiler.target>17</maven.compiler.target>    
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>  
  </properties>  
  <dependencies>    
    <dependency>      
      <groupId>junit</groupId>      
      <artifactId>junit</artifactId>      
      <version>4.13.2</version>      
      <scope>test</scope>    
    </dependency>  
  </dependencies>
</project>
